### ISSUE TITLE
Pin

### ISSUE THREAD

**Issue by Yuri6037** [Manishearth/elsa#23]
I've read the current implementation of FrozenMap and I think the use of StableDeref could be replaced by Pin.

Is there any reason why Pin isn't used instead?

**Comment by Manishearth** [comment]
Because we're trying to be generic over storage mechanism here. I don't recall the exact reasons but I've considered it in the past and didn't see a way for it to work well. If you would like me to consider this you'd have to provide more detail on precisely what you're envisioning API-wise.

(but it's unlikely to be accepted, I think)
